ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_ticket VARCHAR(255) NULL;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS knowledge INT NOT NULL DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN IF NOT EXISTS stats_setup_done TINYINT(1) NOT NULL DEFAULT 0;
